apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: aplicacioncilla
data:
  DB_HOST: "mysql.aplicacioncilla.svc.cluster.local"
  DB_USER: "root"
  DB_NAME: "aplicacioncilla"
  DB_PASSWORD: "root"
